#ifndef LIBSENC_ERROR
#define LIBSENC_ERROR

#define			SENC_ERROR_ECARDS												0x10000000

//°å¿¨·µ»Ø´íÎóÂë
#define			SENC_CMD_STATECODE_SUCCUSS										0x0000

#define			SENC_CMD_STATECODE_USB_DEVICE_BUSY								0x0001
#define			SENC_CMD_STATECODE_USB_DATA_SENDING_FAIL						0x0002
#define			SENC_CMD_STATECODE_PROTOCOL_HEAD_ERROR							0x0003
#define			SENC_CMD_STATECODE_PROTOCOL_LENGTH_ERROR						0x0004
#define			SENC_CMD_STATECODE_PROTOCOL_CMD_TYPE_ERROR						0x0005
#define			SENC_CMD_STATECODE_PROTOCOL_MAC_ERROR							0x0006
#define			SENC_CMD_STATECODE_PROTOCOL_OP_TYPE_ERROR						0x0007
#define			SENC_CMD_STATECODE_PROTOCOL_SECURE_SIGN_ERROR					0x0008
#define			SENC_CMD_STATECODE_CARD_STATE_ERROR								0x0009
#define			SENC_CMD_STATECODE_WRITE_ERROR									0x000A
#define			SENC_CMD_STATECODE_READ_ERROR									0x000B
#define			SENC_CMD_STATECODE_SESSION_KEY_ERROR							0x000C
#define			SENC_CMD_STATECODE_PROTOCOL_ATTRIBUTE_ERROR						0x000D

#define			SENC_CMD_STATECODE_ALGORITHM_RANDOM_NUM_ERROR					0x1001
#define			SENC_CMD_STATECODE_ALGORITHM_AES_ERROR							0x1002
#define			SENC_CMD_STATECODE_ALGORITHM_RSA_ERROR							0x1003
#define			SENC_CMD_STATECODE_ALGORITHM_DES_ERROR							0x1004

#define			SENC_CMD_STATECODE_IC_CARD_NOT_EXIST							0x2001
#define			SENC_CMD_STATECODE_IC_CARD_VERIFIED								0x2002

#define			SENC_CMD_STATECODE_MASTER_CARD_NOT_ADDED						0x3001
#define			SENC_CMD_STATECODE_MASTER_CARD_FULL								0x3002
#define			SENC_CMD_STATECODE_MASTER_CARD_NOT_EXIST						0x3003
#define			SENC_CMD_STATECODE_MASTER_CARD_VERIFY_FAILED					0x3004
#define			SENC_CMD_STATECODE_MASTER_CARD_VERIFIED							0x3005
#define			SENC_CMD_STATECODE_MASTER_CARD_ADDED							0x3006

#define			SENC_CMD_STATECODE_DONGLE_EXISTED								0x4001
#define			SENC_CMD_STATECODE_DONGLE_NOT_EXIST								0x4002
#define			SENC_CMD_STATECODE_DONGLE_ID_ERROR								0x4003
#define			SENC_CMD_STATECODE_DONGLE_VERIFY_FAILED							0x4004
#define			SENC_CMD_STATECODE_DONGLE_STORAGE_FULL							0x4005

#define			SENC_CMD_STATECODE_KEY_INDEX_ERROR								0x5001
#define			SENC_CMD_STATECODE_KEY_ALG_TYPE_ERROR							0x5002
#define			SENC_CMD_STATECODE_KEY_NOT_EXIST								0x5003
#define			SENC_CMD_STATECODE_KEY_EXISTED									0x5004
#define			SENC_CMD_STATECODE_KEY_STORAGE_FULL								0x5005



unsigned int SencErrCheck(unsigned char *Buf);
unsigned int SencRetCheck(unsigned char *Buf, unsigned int *ReceiveLength, unsigned int CheckCode);
int SencUsbErrorCheck(int cc);
unsigned int ErrorLog(unsigned int ErrCode,char* tag,char* file, int line );

#define ERROR_LOG(a,b)				ErrorLog(a, (char*)b, __FILE__, __LINE__)







#endif  //LIBSENC_ERROR_H_